<?php

use Magento\Framework\Escaper;
use DeveloperHub\OrderNote\Block\Order\Note;

/** @var Escaper $escaper */
/** @var Note $block */

?>
<?php if ($block->showNoteInAccount()): ?>
    <?php if ($note = $block->getOrderNote()): ?>
        <div class="block block-order-note order-note-block">
            <div class="block-content">
                <div class="block-title">
                    <strong><?= $escaper->escapeHtml(__('Order Note')) ?></strong>
                </div>
                <div class="box-content">
                    <?= $block->getOrderNoteHtml(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
